// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-p0VD3bjf1MVcPsf6dFF6jogqiheJZU',
    appId: '1:57548327918:web:e95e6c5144b33a7a301cff',
    messagingSenderId: '57548327918',
    projectId: 'islanderchat',
    authDomain: 'islanderchat.firebaseapp.com',
    storageBucket: 'islanderchat.firebasestorage.app',
    measurementId: 'G-SCZK15PWYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGYwBNeBbsxz13MoiEpFZokoydSEsh_k',
    appId: '1:57548327918:android:bb8bfcf1f6599072301cff',
    messagingSenderId: '57548327918',
    projectId: 'islanderchat',
    storageBucket: 'islanderchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhy201c_w2uQjyqZ07ZjBDA38Qu7PMkks',
    appId: '1:57548327918:ios:1cba842e27f59a13301cff',
    messagingSenderId: '57548327918',
    projectId: 'islanderchat',
    storageBucket: 'islanderchat.firebasestorage.app',
    iosBundleId: 'com.example.islanderChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhy201c_w2uQjyqZ07ZjBDA38Qu7PMkks',
    appId: '1:57548327918:ios:1cba842e27f59a13301cff',
    messagingSenderId: '57548327918',
    projectId: 'islanderchat',
    storageBucket: 'islanderchat.firebasestorage.app',
    iosBundleId: 'com.example.islanderChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI-p0VD3bjf1MVcPsf6dFF6jogqiheJZU',
    appId: '1:57548327918:web:61c085795dc533e9301cff',
    messagingSenderId: '57548327918',
    projectId: 'islanderchat',
    authDomain: 'islanderchat.firebaseapp.com',
    storageBucket: 'islanderchat.firebasestorage.app',
    measurementId: 'G-MFV1J2QFW9',
  );
}
